plugins:
  editorconfig:
    enabled: true
  markdownlint:
    enabled: true
    config:
      default: true
      MD007: false # Disable MD007 (Unordered list indentation)
      MD013: false # Disable MD013 (Line length)
      MD029: false # Disable MD029 (Ordered list item prefix)
  pylint:
    enabled: false
  sonar-python:
    enabled: true
  fixme:
    enabled: true
  git-legal:
    enabled: true
  shellcheck:
    enabled: true
  bandit:
    enabled: true
  pep8:
    enabled: false
  radon:
    enabled: true
    config:
      threshold: C
version: "2"
checks:
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 10
