# This file overrides the built-in prettier style from nitpick so that
# pre-commit will not thow a deprecation warning.
style:
  files:
    .pre-commit-config.yaml:
      - repo: https://github.com/pre-commit/mirrors-prettier
        hooks:
          - id: prettier
            stages:
              - pre-commit
