# strangebasisdevs core flake8 config
[nitpick.meta]
name = "flake8"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/style/flake8.toml"

[nitpick.styles]
include = [
    "py://nitpick/resources/python/flake8",
]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/flake8"

[[".pre-commit-config.yaml".repos.hooks]]
id = "flake8"
additional_dependencies = ["flake8-blind-except", "flake8-bugbear", "flake8-comprehensions", "flake8-debugger", "flake8-docstrings", "flake8-isort", "flake8-polyfill", "flake8-pytest", "flake8-quotes", "flake8-typing-imports", "yesqa", "nitpick"]
