[nitpick.meta]
name = "strangebasis-github-workflow"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/strangebasis-github-workflow.toml"

[".github/workflows/python.yaml"]
name = "Python"
on = ["push", "pull_request"]

[".github/workflows/python.yaml".jobs.build.strategy]
fail-fast = false

[".github/workflows/python.yaml".jobs.build.strategy.matrix]
os = ["ubuntu-latest", "windows-latest", "macos-latest"]
python-version = ["3.12",]

[".github/workflows/python.yaml".jobs.build]
name = "${{ matrix.python-version }} ${{ matrix.os }}"
runs-on = "${{ matrix.os }}"

[".github/workflows/python.yaml".jobs.build.env]
PYTHONUNBUFFERED = 1

[[".github/workflows/python.yaml".jobs.build.steps]]
name = "Checkout"
uses = "actions/checkout@v3"

[[".github/workflows/python.yaml".jobs.build.steps]]
name = "Set up Python ${{ matrix.python-version }}"
uses = "actions/setup-python@v4"

[".github/workflows/python.yaml".jobs.build.steps.with]
python-version = "${{ matrix.python-version }}"

[[".github/workflows/python.yaml".jobs.build.steps]]
name = "Install poetry"
run = "python -m pip install poetry"

[[".github/workflows/python.yaml".jobs.build.steps]]
name = "Install dependencies"
run = "poetry install"

[[".github/workflows/python.yaml".jobs.build.steps]]
name = "Run tests"
run = "poetry run pytest"
