[nitpick.meta]
name = "strangebasis-nitpick"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/strangebasis-nitpick.toml"

["pyproject.toml".tool.nitpick]
style = [
    "py://nitpick/resources/any/codeclimate",
    "py://nitpick/resources/any/commitizen",
    "py://nitpick/resources/any/editorconfig",
    "py://nitpick/resources/any/git-legal",
    "py://nitpick/resources/any/pre-commit-hooks",
    "py://nitpick/resources/javascript/package-json",
    "py://nitpick/resources/markdown/markdownlint",
    "py://nitpick/resources/python/absent",
    "py://nitpick/resources/python/autoflake",
    "py://nitpick/resources/python/bandit",
    "py://nitpick/resources/python/black",
    "py://nitpick/resources/python/flake8",
    "py://nitpick/resources/python/poetry",
    "py://nitpick/resources/python/pre-commit-hooks",
    "py://nitpick/resources/python/radon",
    "py://nitpick/resources/python/sonar-python",
    "py://nitpick/resources/python/312",
    "py://nitpick/resources/shell/bashate",
    "py://nitpick/resources/shell/shellcheck",
]

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/PyCQA/flake8"

[[".pre-commit-config.yaml".repos.hooks]]
id = "flake8"
additional_dependencies = [
    "flake8-blind-except",
    "flake8-bugbear",
    "flake8-comprehensions",
    "flake8-debugger",
    "flake8-docstrings",
    "flake8-isort",
    "flake8-polyfill",
    "flake8-pytest",
    "flake8-quotes",
    "flake8-typing-imports",
    "yesqa",
    "nitpick"
]
