[nitpick.meta]
name = "strangebasis-prettier"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/strangebasis-prettier.toml"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/mirrors-prettier"

[[".pre-commit-config.yaml".repos.hooks]]
id = "prettier"
stages = ["pre-commit"]
