[nitpick.meta]
name = "style"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/style.toml"

[nitpick.styles]
include = [
    "style/flake8.toml",
    "style/isort.toml",
    "style/mypy.toml",
    "style/prettier.toml",
    "style/pylint.toml",
    "py://nitpick/resources/python/autoflake",
    "py://nitpick/resources/python/black",
]
