[nitpick.meta]
name = "core"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/core.toml"

[nitpick.styles]
include = [
    # "core/actions.toml",
    "core/bashate.toml",
    "core/commitizen.toml",
    "core/editorconfig.toml",
    "core/gitlegal.toml",
    "core/precommit.toml",
    "core/pygrep.toml",
    "py://nitpick/resources/python/bandit",
    "py://nitpick/resources/shell/shellcheck",
]
