# strangebasisdevs core pygrep config
[nitpick.meta]
name = "pygrep"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/core/pygrep.toml"

[[".pre-commit-config.yaml".repos]]
repo = "https://github.com/pre-commit/pygrep-hooks"
rev = "v1.10.0"
hooks = [
    {id = "python-check-mock-methods"},
    {id = "rst-backticks"}
]
