# strangebasisdevs core EditorConfig config
[nitpick.meta]
name = "editorconfig"
url = "https://github.com/strangebasisdevs/strangebasis/blob/main/nitpick/core/editorconfig.toml"

[".editorconfig"]
# top-most EditorConfig file
root = true

[".editorconfig"."*"]
# Unix-style newlines with a newline ending every file
charset = "utf-8"
end_of_line = "lf"
indent_size = 4
indent_style = "space"
insert_final_newline = true
trim_trailing_whitespace = true

[".editorconfig"."*.{bat,cmd,ps1}"]
end_of_line = "crlf"

[".editorconfig"."*.{js,json,json5,yml,yaml,md,rb}"]
indent_size = 2

[".editorconfig".Makefile]
indent_style = "tab"

[".editorconfig"."*.md"]
indent_style = "space"
indent_size = 1
insert_final_newline = true
trim_trailing_whitespace = true

[".editorconfig".LICENSE]
indent_size = "unset"

[".codeclimate.yml".plugins.editorconfig]  # https://docs.codeclimate.com/docs/editorconfig
enabled = true
