# This "Strange Basis" is my digital toolbox. Use at your own risk.
#     Copyright (C) 2024  Skylar DonLevy

"""Tests for the cookiecutter generation of projects using the local directory structure."""
import os
import shutil
import subprocess

import pytest


@pytest.mark.parametrize("output_dir", ["strangebasis-derivative"])
def test_cookiecutter_project_creation(output_dir: str) -> None:
    """
    Test running cookiecutter on the local directory structure.

    Args:
        output_dir (str): The name of the directory to be generated by cookiecutter.
    """
    try:
        # Run cookiecutter on the current directory with no input
        subprocess.run(["cookiecutter", ".", "--no-input"], check=True)
    except subprocess.CalledProcessError as e:
        pytest.fail(f"Cookiecutter command failed: {e}")

    try:
        # Verify that the project directory was created
        assert os.path.isdir(output_dir)

        # Optionally, check for existence of expected files
        expected_files = ["README.md", "pyproject.toml"]
        for file in expected_files:
            assert os.path.isfile(os.path.join(output_dir, file))

    finally:
        # Clean up by removing the generated directory
        if os.path.isdir(output_dir):
            shutil.rmtree(output_dir)

        # Print instructions for manually testing the generated project
        print(
            "To manually test the generated project, navigate to " f"'{output_dir}' and run your desired test commands."
        )
